baseURL = "https://sergi.xaudiera.xyz"
languageCode = "en-us"
title = "Sergi Xaudiera"
author = "Sergi Xaudiera"
theme = "sx"
enableGitInfo = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
